/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoDatos.CiudadData;
import java.util.ArrayList;
import java.util.List;
import Entidades.Ciudad;

/**
 *
 * @author Administrador
 */
public class Despegar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Despegar
     */
    public Despegar() {
        initComponents();
        CargarCiudades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_Ventana = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Desplegable_Catidad_Habitantes = new javax.swing.JSpinner();
        titulo_Origen = new javax.swing.JLabel();
        Desplegable_Origen = new javax.swing.JComboBox<>();
        Flecha_Simbolo = new javax.swing.JLabel();
        titulo_Destino = new javax.swing.JLabel();
        Desplegable_Destino = new javax.swing.JComboBox<>();
        titulo_fecha_ida = new javax.swing.JLabel();
        Desplegable_fecha_ida = new com.toedter.calendar.JDateChooser();
        titulo_fecha_vuelta = new javax.swing.JLabel();
        Desplegable_fecha_vuelta = new com.toedter.calendar.JDateChooser();
        Titulo_Catidad_Persona = new javax.swing.JLabel();
        Desplegable_Catidad_Persona = new javax.swing.JSpinner();
        Titulo_Catidad_Habitantes = new javax.swing.JLabel();
        BuscarPaquetes = new javax.swing.JButton();

        setForeground(java.awt.Color.white);

        Titulo_Ventana.setText("Paquetes turísticos ");
        Titulo_Ventana.setMaximumSize(new java.awt.Dimension(94, 20));
        Titulo_Ventana.setMinimumSize(new java.awt.Dimension(94, 20));

        titulo_Origen.setText("ORIGEN");
        titulo_Origen.setPreferredSize(new java.awt.Dimension(39, 44));

        Desplegable_Origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Desplegable_Origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desplegable_OrigenActionPerformed(evt);
            }
        });

        Flecha_Simbolo.setText("➡");

        titulo_Destino.setText("DESTINO");

        Desplegable_Destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        titulo_fecha_ida.setText("Fecha de Ida");

        titulo_fecha_vuelta.setText("Fecha de Vuelta");

        Titulo_Catidad_Persona.setText("Personas");

        Titulo_Catidad_Habitantes.setText("Habitaciones");

        BuscarPaquetes.setText("Buscar");
        BuscarPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarPaquetesMouseClicked(evt);
            }
        });
        BuscarPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPaquetesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Desplegable_Catidad_Persona, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(Titulo_Catidad_Persona)))
                            .addComponent(titulo_Origen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Desplegable_fecha_ida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(titulo_fecha_ida)
                                .addGap(122, 122, 122))
                            .addComponent(Desplegable_Origen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Flecha_Simbolo)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titulo_Destino)
                                    .addComponent(Desplegable_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(titulo_fecha_vuelta)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Desplegable_fecha_vuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Desplegable_Catidad_Habitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Titulo_Catidad_Habitantes))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BuscarPaquetes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_Origen, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo_Destino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Desplegable_Origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Flecha_Simbolo)
                    .addComponent(Desplegable_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo_fecha_vuelta)
                    .addComponent(titulo_fecha_ida, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Desplegable_fecha_ida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Desplegable_fecha_vuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulo_Catidad_Habitantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Desplegable_Catidad_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Desplegable_Catidad_Habitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Titulo_Catidad_Persona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(BuscarPaquetes)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(Titulo_Ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo_Ventana, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Desplegable_OrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desplegable_OrigenActionPerformed
          
    }//GEN-LAST:event_Desplegable_OrigenActionPerformed

    private void BuscarPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPaquetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarPaquetesActionPerformed

    private void BuscarPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarPaquetesMouseClicked
        // TODO add your handling code here:
        
        
        ArrayList<Object> datos = new ArrayList<>();

// Obtener los valores de los JSpinners
datos.add(Desplegable_Catidad_Habitantes.getValue());
datos.add(Desplegable_Catidad_Persona.getValue());

// Obtener los valores seleccionados en los JComboBox
datos.add(Desplegable_Destino.getSelectedItem());
datos.add(Desplegable_Origen.getSelectedItem());

// Obtener las fechas seleccionadas en los JDateChoosers
datos.add(Desplegable_fecha_ida.getDate());
datos.add(Desplegable_fecha_vuelta.getDate());

// Imprimir los datos en la consola
for (Object dato : datos) {
    System.out.println(dato);
}

        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_BuscarPaquetesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarPaquetes;
    private javax.swing.JSpinner Desplegable_Catidad_Habitantes;
    private javax.swing.JSpinner Desplegable_Catidad_Persona;
    private javax.swing.JComboBox<String> Desplegable_Destino;
    private javax.swing.JComboBox<String> Desplegable_Origen;
    private com.toedter.calendar.JDateChooser Desplegable_fecha_ida;
    private com.toedter.calendar.JDateChooser Desplegable_fecha_vuelta;
    private javax.swing.JLabel Flecha_Simbolo;
    private javax.swing.JLabel Titulo_Catidad_Habitantes;
    private javax.swing.JLabel Titulo_Catidad_Persona;
    private javax.swing.JLabel Titulo_Ventana;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titulo_Destino;
    private javax.swing.JLabel titulo_Origen;
    private javax.swing.JLabel titulo_fecha_ida;
    private javax.swing.JLabel titulo_fecha_vuelta;
    // End of variables declaration//GEN-END:variables

public void CargarCiudades(){
     Desplegable_Origen.removeAllItems();
     Desplegable_Destino.removeAllItems();
     CiudadData c = new CiudadData();
     List ciudades = c.listarCiudad2();
        for(int i=0;i<ciudades.size();i++){
            String nombreCiudad = ((Ciudad)ciudades.get(i)).getNombre() +", "+((Ciudad)ciudades.get(i)).getProvincia()+", "+((Ciudad)ciudades.get(i)).getPais();
            Desplegable_Origen.addItem(nombreCiudad);
            Desplegable_Destino.addItem(nombreCiudad);
       }  
        
}

}
