/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoDatos.CiudadData;
import java.util.ArrayList;
import java.util.List;
import Entidades.Ciudad;

/**
 *
 * @author Administrador
 */
public class Despegar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Despegar
     */
    public Despegar() {
        initComponents();
        CargarCiudades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        Desplegable_Catidad_Habitantes = new javax.swing.JSpinner();
        titulo_Origen = new javax.swing.JLabel();
        Desplegable_Origen = new javax.swing.JComboBox<>();
        Flecha_Simbolo = new javax.swing.JLabel();
        titulo_Destino = new javax.swing.JLabel();
        Desplegable_Destino = new javax.swing.JComboBox<>();
        titulo_fecha_ida = new javax.swing.JLabel();
        Desplegable_fecha_ida = new com.toedter.calendar.JDateChooser();
        titulo_fecha_vuelta = new javax.swing.JLabel();
        Desplegable_fecha_vuelta = new com.toedter.calendar.JDateChooser();
        Titulo_Catidad_Persona = new javax.swing.JLabel();
        Desplegable_Catidad_Persona = new javax.swing.JSpinner();
        Titulo_Catidad_Habitantes = new javax.swing.JLabel();
        Btnb = new javax.swing.JButton();
        Titulo_Ventana = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(0, 21, 79));

        titulo_Origen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titulo_Origen.setForeground(new java.awt.Color(244, 175, 27));
        titulo_Origen.setText("ORIGEN");
        titulo_Origen.setPreferredSize(new java.awt.Dimension(39, 44));

        Desplegable_Origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Desplegable_Origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desplegable_OrigenActionPerformed(evt);
            }
        });

        Flecha_Simbolo.setText("➡");

        titulo_Destino.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titulo_Destino.setForeground(new java.awt.Color(244, 175, 27));
        titulo_Destino.setText("DESTINO");

        Desplegable_Destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        titulo_fecha_ida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titulo_fecha_ida.setForeground(new java.awt.Color(244, 175, 27));
        titulo_fecha_ida.setText("Fecha de Ida");

        titulo_fecha_vuelta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titulo_fecha_vuelta.setForeground(new java.awt.Color(244, 175, 27));
        titulo_fecha_vuelta.setText("Fecha de Vuelta");

        Titulo_Catidad_Persona.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Titulo_Catidad_Persona.setForeground(new java.awt.Color(244, 175, 27));
        Titulo_Catidad_Persona.setText("Personas");

        Titulo_Catidad_Habitantes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Titulo_Catidad_Habitantes.setForeground(new java.awt.Color(244, 175, 27));
        Titulo_Catidad_Habitantes.setText("Habitaciones");

        Btnb.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Btnb.setForeground(new java.awt.Color(244, 175, 27));
        Btnb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/Imagen1.png"))); // NOI18N
        Btnb.setContentAreaFilled(false);
        Btnb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btnb.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/Imagengato fuerte.png"))); // NOI18N
        Btnb.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/Imagengato fuerte.png"))); // NOI18N
        Btnb.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Btnb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnbMouseExited(evt);
            }
        });
        Btnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbActionPerformed(evt);
            }
        });

        Titulo_Ventana.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Titulo_Ventana.setForeground(new java.awt.Color(244, 175, 27));
        Titulo_Ventana.setText("PAQUETES TURÍSTICOS");
        Titulo_Ventana.setMaximumSize(new java.awt.Dimension(94, 20));
        Titulo_Ventana.setMinimumSize(new java.awt.Dimension(94, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Desplegable_Origen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(titulo_fecha_ida))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(Desplegable_fecha_ida, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(Desplegable_Catidad_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(Titulo_Catidad_Persona)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Desplegable_fecha_vuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(titulo_fecha_vuelta))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Titulo_Catidad_Habitantes)
                                            .addComponent(Desplegable_Catidad_Habitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Flecha_Simbolo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Desplegable_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 25, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(titulo_Origen, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241)
                        .addComponent(titulo_Destino)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo_Ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(Btnb, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Titulo_Ventana, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_Origen, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo_Destino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Desplegable_Origen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Desplegable_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Flecha_Simbolo))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_fecha_ida)
                    .addComponent(titulo_fecha_vuelta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Desplegable_fecha_ida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Desplegable_fecha_vuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo_Catidad_Persona)
                    .addComponent(Titulo_Catidad_Habitantes))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Desplegable_Catidad_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Desplegable_Catidad_Habitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(Btnb, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Desplegable_OrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desplegable_OrigenActionPerformed
          
    }//GEN-LAST:event_Desplegable_OrigenActionPerformed

    private void BtnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnbActionPerformed

    private void BtnbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnbMouseClicked
        // TODO add your handling code here:
        
        
        ArrayList<Object> datos = new ArrayList<>();

// Obtener los valores de los JSpinners
datos.add(Desplegable_Catidad_Habitantes.getValue());
datos.add(Desplegable_Catidad_Persona.getValue());

// Obtener los valores seleccionados en los JComboBox
datos.add(Desplegable_Destino.getSelectedItem());
datos.add(Desplegable_Origen.getSelectedItem());

// Obtener las fechas seleccionadas en los JDateChoosers
datos.add(Desplegable_fecha_ida.getDate());
datos.add(Desplegable_fecha_vuelta.getDate());

// Imprimir los datos en la consola
for (Object dato : datos) {
    System.out.println(dato);
}

        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_BtnbMouseClicked

    private void BtnbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnbMouseEntered
 Btnb.setText("Buscar");
    }//GEN-LAST:event_BtnbMouseEntered

    private void BtnbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnbMouseExited
        Btnb.setText("");
    }//GEN-LAST:event_BtnbMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnb;
    private javax.swing.JSpinner Desplegable_Catidad_Habitantes;
    private javax.swing.JSpinner Desplegable_Catidad_Persona;
    private javax.swing.JComboBox<String> Desplegable_Destino;
    private javax.swing.JComboBox<String> Desplegable_Origen;
    private com.toedter.calendar.JDateChooser Desplegable_fecha_ida;
    private com.toedter.calendar.JDateChooser Desplegable_fecha_vuelta;
    private javax.swing.JLabel Flecha_Simbolo;
    private javax.swing.JLabel Titulo_Catidad_Habitantes;
    private javax.swing.JLabel Titulo_Catidad_Persona;
    private javax.swing.JLabel Titulo_Ventana;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titulo_Destino;
    private javax.swing.JLabel titulo_Origen;
    private javax.swing.JLabel titulo_fecha_ida;
    private javax.swing.JLabel titulo_fecha_vuelta;
    // End of variables declaration//GEN-END:variables

public void CargarCiudades(){
     Desplegable_Origen.removeAllItems();
     Desplegable_Destino.removeAllItems();
     CiudadData c = new CiudadData();
     List ciudades = c.listarCiudad2();
        for(int i=0;i<ciudades.size();i++){
            String nombreCiudad = ((Ciudad)ciudades.get(i)).getNombre() +", "+((Ciudad)ciudades.get(i)).getProvincia()+", "+((Ciudad)ciudades.get(i)).getPais();
            Desplegable_Origen.addItem(nombreCiudad);
            Desplegable_Destino.addItem(nombreCiudad);
       }  
        
}

}
