/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoDatos.CiudadData;
import AccesoDatos.Conexion;
import AccesoDatos.PasajeData2;
import static AccesoDatos.PasajeData2.guardarPasaje;
import Entidades.Alojamiento;
import Entidades.Ciudad;
import Entidades.Cliente;
import Entidades.Paquete;
import Entidades.Pasaje;
import Entidades.Reserva;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class InsertPasaje extends javax.swing.JInternalFrame {
      ArrayList<Object> BaseDatos ;
      ArrayList<Alojamiento> ListarAlojamiento ;
      ArrayList<Ciudad> ListarCiudad ;
      ArrayList<Cliente> ListarCliente ;
      ArrayList<Paquete> ListarPaquete ;
      ArrayList<Pasaje> ListarPasaje ;
      ArrayList<Reserva> ListarReserva ;
    private final Connection con;
    private List<Pasaje> guardarPasaje = new ArrayList<>();


    /**
     * Creates new form InsertPasaje
     */
    public InsertPasaje(ArrayList<Object> BaseDatos) {
        this.BaseDatos = BaseDatos;
        ListarAlojamiento= ( ArrayList<Alojamiento>) this.BaseDatos.get(0);
        ListarCiudad= ( ArrayList<Ciudad>) this.BaseDatos.get(1);
        ListarCliente= ( ArrayList<Cliente>) this.BaseDatos.get(2);
        ListarPaquete= ( ArrayList<Paquete>) this.BaseDatos.get(3);
        ListarPasaje= ( ArrayList<Pasaje>) this.BaseDatos.get(4);
        ListarReserva= ( ArrayList<Reserva>) this.BaseDatos.get(5);
        
        initComponents();
        this.con=Conexion.getConexion(); 
        Connection conexion = Conexion.getConexion();
        
        CiudadData ciudadData = new CiudadData(Conexion.getConexion()); 
        DefaultComboBoxModel<String> ciudadDestino = new DefaultComboBoxModel<>();
        List<Ciudad> ciudades = ciudadData.listarCiudad(); 
        
        for (Ciudad ciudad : ciudades) {
        ciudadDestino.addElement(ciudad.getNombre());
        }
        CiudadDestino.setModel(ciudadDestino);
        
        DefaultComboBoxModel<String> ciudadOrigenModel = new DefaultComboBoxModel<>();
        for (Ciudad ciudad : ciudades) {
        ciudadOrigenModel.addElement(ciudad.getNombre());
        }
        CiudadOrigen.setModel(ciudadOrigenModel);

        DefaultComboBoxModel<String> estadoModel = new DefaultComboBoxModel<>();
        estadoModel.addElement("0"); 
        estadoModel.addElement("1"); 
        estado.setModel(estadoModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDCFechaida = new com.toedter.calendar.JDateChooser();
        jDCFechav = new com.toedter.calendar.JDateChooser();
        tipoTransporte = new javax.swing.JTextField();
        estado = new javax.swing.JComboBox<>();
        importe = new javax.swing.JTextField();
        CiudadOrigen = new javax.swing.JComboBox<>();
        CiudadDestino = new javax.swing.JComboBox<>();
        Insert = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Nuevo pasaje");

        jLabel2.setText("Tipo de transporte:");

        jLabel3.setText("Fecha de ida");

        jLabel4.setText("Fecha de vuelta");

        jLabel5.setText("Estado:");

        jLabel6.setText("Importe:");

        jLabel7.setText("Ciudad Origen:");

        jLabel8.setText("Ciudad Destino:");

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CiudadOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CiudadDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        jLabel9.setText("Ingrese:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDCFechaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jDCFechav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCFechaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCFechav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Insert)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:      
      String tipoTransportes = tipoTransporte.getText();
    java.util.Date utilFechaI = jDCFechaida.getDate();
    java.util.Date utilFechaF = jDCFechav.getDate();
    LocalDate Fechai = utilFechaI.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate Fechav = utilFechaF.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    int estadoPasaje = Integer.parseInt(estado.getSelectedItem().toString());
    double importePasaje = Double.parseDouble(importe.getText());
    String ciudadOrigen = CiudadOrigen.getSelectedItem().toString();
    String ciudadDestino = CiudadDestino.getSelectedItem().toString();

    Pasaje nuevoPasaje = new Pasaje();
    nuevoPasaje.setTipoTransporte(tipoTransportes);
    nuevoPasaje.setFechaI(Fechai);
    nuevoPasaje.setFechaV(Fechav);
    nuevoPasaje.setEstado(estadoPasaje);
    nuevoPasaje.setImporte(importePasaje);

    Ciudad ciudadO = null;
    Ciudad ciudadD = null;

    for (Ciudad ciudad : ListarCiudad) {
        if (ciudad.getNombre().equals(ciudadOrigen)) {
            ciudadO = ciudad;
        }
        if (ciudad.getNombre().equals(ciudadDestino)) {
            ciudadD = ciudad;
        }

        if (ciudadO != null && ciudadD != null) {
            break;
        }
    }
    nuevoPasaje.setCOrigen(ciudadO);
    nuevoPasaje.setCDestino(ciudadD);

    // Llama al método agregarPasaje de PasajeData para guardar el pasaje en la base de datos
    PasajeData2 pasajeData = new PasajeData2(con);
    PasajeData2.guardarPasaje(nuevoPasaje); // Llamada al método para guardar el pasaje en la base de datos

// Ahora no hay una comparación en el if
    JOptionPane.showMessageDialog(this, "Pasaje insertado correctamente en la base de datos.");

   
   
    }//GEN-LAST:event_InsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CiudadDestino;
    private javax.swing.JComboBox<String> CiudadOrigen;
    private javax.swing.JButton Insert;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JTextField importe;
    private com.toedter.calendar.JDateChooser jDCFechaida;
    private com.toedter.calendar.JDateChooser jDCFechav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tipoTransporte;
    // End of variables declaration//GEN-END:variables
}
