/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoDatos.CiudadData;
import AccesoDatos.Conexion;
import Entidades.Ciudad;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class InsertCiudad extends javax.swing.JInternalFrame {

    /**
     * Creates new form InsertCiudad
     */
    public InsertCiudad() {
        initComponents();
        Estadojbc();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_ciudad = new javax.swing.JLabel();
        Insert_Ciudad_ = new javax.swing.JTextField();
        Titulo_provincia = new javax.swing.JLabel();
        Insert_Provincia_ = new javax.swing.JTextField();
        Titulo_pais = new javax.swing.JLabel();
        Insert_Pais_ = new javax.swing.JTextField();
        Titulo_ = new javax.swing.JLabel();
        Insert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Estado = new javax.swing.JComboBox<>();

        Titulo_ciudad.setText("Ingrese Ciudad:");

        Titulo_provincia.setText("Ingrese Provincia:");

        Titulo_pais.setText("Ingrese Pais:");

        Titulo_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Titulo_.setText("CargarCiudad");

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado:");

        Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo_)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo_ciudad)
                            .addComponent(Titulo_pais)
                            .addComponent(Titulo_provincia)
                            .addComponent(jLabel1))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Insert_Ciudad_)
                            .addComponent(Insert_Provincia_)
                            .addComponent(Insert_Pais_, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo_)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert_Ciudad_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo_ciudad))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo_provincia)
                    .addComponent(Insert_Provincia_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo_pais)
                    .addComponent(Insert_Pais_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Insert)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:                                   
      String nombre = Insert_Ciudad_.getText();
      String provincia = Insert_Provincia_.getText();
      String pais = Insert_Pais_.getText();
      String estadoCiudad = (String) Estado.getSelectedItem();
      boolean estado = estadoCiudad.equals("1");

      Ciudad nuevaCiudad = new Ciudad();
      nuevaCiudad.setNombre(nombre);
      nuevaCiudad.setProvincia(provincia);
      nuevaCiudad.setPais(pais);
      nuevaCiudad.setEstado(estado);


      CiudadData ciudadData = new CiudadData(Conexion.getConexion());

      ciudadData.guardarCiudad(nuevaCiudad);
     
    }//GEN-LAST:event_InsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Estado;
    private javax.swing.JButton Insert;
    private javax.swing.JTextField Insert_Ciudad_;
    private javax.swing.JTextField Insert_Pais_;
    private javax.swing.JTextField Insert_Provincia_;
    private javax.swing.JLabel Titulo_;
    private javax.swing.JLabel Titulo_ciudad;
    private javax.swing.JLabel Titulo_pais;
    private javax.swing.JLabel Titulo_provincia;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

  private void Estadojbc(){
      DefaultComboBoxModel<String> estadoModel = new DefaultComboBoxModel<>();
      estadoModel.addElement("0"); 
      estadoModel.addElement("1"); 
      Estado.setModel(estadoModel);       
   }
}

