/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoDatos.CiudadData;
import AccesoDatos.PaqueteData;
import AccesoDatos.PasajeData;
import AccesoDatos.ReservaData;
import Entidades.*;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class VistaPaquete extends javax.swing.JInternalFrame {
    ArrayList<Object> BaseDatos ;
    ArrayList<Alojamiento> ListarAlojamiento ;
    ArrayList<Ciudad> ListarCiudad ;
    ArrayList<Cliente> ListarCliente ;
    ArrayList<Paquete> ListarPaquete ;
    ArrayList<Pasaje> ListarPasaje ;
    ArrayList<Reserva> ListarReserva ;
    /**
     * Creates new form NewJInternalFrame
     */
   
       
    public VistaPaquete() {
    }

    public VistaPaquete(ArrayList<Object> BaseDatos) {
        this.BaseDatos = BaseDatos;
        ListarAlojamiento= ( ArrayList<Alojamiento>) this.BaseDatos.get(0);
        ListarCiudad= ( ArrayList<Ciudad>) this.BaseDatos.get(1);
        ListarCliente= ( ArrayList<Cliente>) this.BaseDatos.get(2);
        ListarPaquete= ( ArrayList<Paquete>) this.BaseDatos.get(3);
        ListarPasaje= ( ArrayList<Pasaje>) this.BaseDatos.get(4);
        ListarReserva= ( ArrayList<Reserva>) this.BaseDatos.get(5);
        //ejecutar apenas aparece main
        initComponents();
        dibujar_Columna();
        modeloDeColocarItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        paquetes_Turisticos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(648, 467));

        paquetes_Turisticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(paquetes_Turisticos);

        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 482, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paquetes_Turisticos;
    // End of variables declaration//GEN-END:variables

    
    
    public void dibujar_Columna(){
        String[] columnNames = {"ID", "Origen", "Destino", "FechaI", "FechaV","Descripcion", "Costo"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        paquetes_Turisticos.setModel(model);
    }
    
    
  public void modeloDeColocarItem(){
    // Obtén el modelo de la tabla
    DefaultTableModel model = (DefaultTableModel) paquetes_Turisticos.getModel();
    // Crea un array con los datos de la fila
   
   
    Object[] row = new Object[7];
    
     for (int i = 0; i<ListarPaquete.size();i++){
         // Ajusta el tamaño del array según el número de columnas de tu tabla
        
        row[0] = /*ID*/ListarPaquete.get(i).getIdPaquete();
        
        
        int  idpasaje =ListarPaquete.get(i).getIdAlojamiento();
        int IdCiudadOrigen=0;
        int IdCiudadDestino=0;
        String CiudadOrigen ="";
        String CiudadDestino ="";
        Date FechaI = null ;
        Date FechaV = null ;
        for(int p = 0 ;p<ListarPasaje.size();p++){
            
            
            
          if (idpasaje==ListarPasaje.get(p).getIdPasaje()){

            
               IdCiudadOrigen = ListarPasaje.get(p).getCiudadOrigen();
               IdCiudadDestino = ListarPasaje.get(p).getCiudadDestino();
               //buscar Ciudad Origen en Pasaje/ciudad/nombre
               for(int c = 0 ; c<ListarCiudad.size();c++){
                   if(ListarCiudad.get(c).getIdCiudad()==IdCiudadOrigen){
                        CiudadOrigen = ListarCiudad.get(c).getNombre()+ " "+ ListarCiudad.get(c).getProvincia()+ " "+ListarCiudad.get(c).getPais() ;
                   }
               }
               //buscar Ciudad Destino en Pasaje/ciudad/nombre
                for(int c = 0 ; c<ListarCiudad.size();c++){
                   if(ListarCiudad.get(c).getIdCiudad()==IdCiudadDestino){
                        CiudadDestino = ListarCiudad.get(c).getNombre()+ " "+ ListarCiudad.get(c).getProvincia()+ " "+ListarCiudad.get(c).getPais() ;
                   }
               }
                
            //buscar Fecha Ida
            FechaI = ListarPasaje.get(p).getFechaIda();
            FechaV =  ListarPasaje.get(p).getFechaVuelta();
            
            // buscar Fecha Ida
            }    
        }
        
        row[1] = /*Origen*/CiudadOrigen;   
        row[2] = /*Destino*/CiudadDestino;
        
        row[3] = /*FechaI*/FechaI;
        row[4] = /*FechaV*/FechaV;
        row[5] = /*Descripcion*/"";
        row[6] = /*Costo*/"";
        
    }
    // Continúa llenando el array con los datos que desees
    // Añade la fila al modelo
     model.addRow(row);
    // Asigna el modelo a la tabla
    paquetes_Turisticos.setModel(model);
  }  


   


  
}

