/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoDatos.paqueteData;
import AccesoDatos.pasajeData;
import AccesoDatos.reservaData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class VistaPaquete extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public VistaPaquete() {
        //ejecutar apenas aparece main
        initComponents();
        dibujar_Columna();
        modeloDeColocarItem();
 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        paquetes_Turisticos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(648, 467));

        paquetes_Turisticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(paquetes_Turisticos);

        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 482, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paquetes_Turisticos;
    // End of variables declaration//GEN-END:variables

    
    
    public void dibujar_Columna(){
        String[] columnNames = {"ID", "Origen", "Destino", "FechaI", "FechaV","Descripcion", "Costo"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        paquetes_Turisticos.setModel(model);
    }
    
    
  public void modeloDeColocarItem(){
    // Obtén el modelo de la tabla
    DefaultTableModel model = (DefaultTableModel) paquetes_Turisticos.getModel();
    // Crea un array con los datos de la fila
    Object[] row = new Object[7];
    reservaData reservas = new reservaData();
     for (int i = 0; i<reservas.listarReserva().size();i++){
         // Ajusta el tamaño del array según el número de columnas de tu tabla
        row[0] = /*IdReserva*/reservas.listarReserva().get(i).getIdReserva();
        int IDpaquete = reservas.listarReserva().get(i).getIdPaquete();
        int IDpasaje = new paqueteData().getCostoPasaje(IDpaquete);
        System.out.println(IDpaquete);
        System.out.println(IDpasaje);
        
        row[1] = /*"Origen"*/new pasajeData().getCiudadOrigen(IDpasaje);
        row[2] = "Destino";
        row[3] = "s";
        row[4] = "FechaV ";
        row[5] = "Descripcion";
        int IDreserva= reservas.listarReserva().get(i).;
        Double costoPasaje=;
        Double Estadia=0.0;
        row[6] = "Costo";
        
    }
    // Continúa llenando el array con los datos que desees
    // Añade la fila al modelo
     model.addRow(row);
    // Asigna el modelo a la tabla
    paquetes_Turisticos.setModel(model);
  }    
}
